# Define the tesseract language
language: eng

# Where the receipts are stored
# Receipts should be simple text files
receipts_path: "data\\txt"

results_as_json: false

# Market names roughly ordered by likelihood.
# Can contain market locations for fuzzy parsing
markets:
   LanThai:
      - lanthai
      - LanThai
      - lanThai

# Sum keys roughly ordered by likelyhood.
sum_keys:
   - total
   - totals
   - sum
   - Sums
   - Sum
   - sums
   - Total
   - Totals
   - lata)
   - Sub Total
   - Sales Tax
   - Total
   - Tip Suggestions

ignore_keys:
   - kg x
   - stkx
   - stk
   - zw-summe

sum_format: '\d+(\.\s?|,\s?|[^a-zA-Z\d])\d{2}'

item_format: '\b(\d+)\s+([A-Za-z\s]+?)\s+(\d+\.\d{2})\b'
item_format_metro: '[0-9]\s(.*?)\d.()((\d|\d{2})(\,|\.)\d{1,2})\s([A|a]|[B|b])'

# Matches dates like 19.08.15 and 19.08.2015
# date_format: '((\d{2}\.\d{2}\.\d{2,4})|(\d{2,4}\/\d{2}\/\d{2})|(\d{2}\/\d{2}\/\d{4}))'
date_format: '\b(0[1-9]|1[0-2])-([0-3]?[0-9])\b'
